# config/packages/doctrine.yaml

doctrine:
    dbal:
        url: '%env(DATABASE_URL)%'

    orm:        
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                
                mappings:
                    SonataUserBundle: ~
                    FOSUserBundle: ~
                    ApplicationToolsBundle: ~
        
                    App:
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        is_bundle: false
                        prefix: App\Entity
                        alias: App