# config/packages/sonata_admin.yaml

sonata_admin:
    title: Prestaciones
    templates:
        layout: 'standard_layout.html.twig'
        #knp_menu_template: '@ApplicationAdmin/Menu/custom_knp_menu.html.twig'
    dashboard:
       groups:
            admin:
                label: 'Servicios'
                icon: '<i class="fa fa-usd"></i>'
                items:  
                    - admin.ordenprestacion                      
                    - admin.visitas
                    - admin.envios                      
            admin1:
                label: 'Configuracion'
                icon: '<i class="fa fa-cogs"></i>'
                items:  
                    - admin.afiliados
                    - admin.sucursales
                    - admin.profesionales
                    - admin.diagnosticos
                    - admin.modulo
                    - admin.montos
                    - route: 'excel'
                      label: 'Excel'
                roles: [ROLE_ADMIN_CONFIG]
            admin2:
                label: 'Gestion de Usuarios'
                icon: '<i class="fa fa-user"></i>'
                items:
                    - sonata.user.admin.user
                    - sonata.user.admin.group
                roles: [ROLE_SUPER_ADMIN]
                
sonata_block:
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]
